### ISSUE TITLE
Organize the list

### ISSUE THREAD

**Issue by kai5263499** [kai5263499/osx-security-awesome#1]
It would be nice if the list were re-organized into tables

**Comment by uzluisf** [comment]
@kai5263499 Do you have any idea on how the tables should look like? One column? Two columns?

**Comment by kai5263499** [comment]
After looking at some other awesome lists it looks like a single column would work. [This](https://github.com/paragonie/awesome-appsec) looks like a good example of what I have in mind.

**Comment by uzluisf** [comment]
That looks like a hierarchical list. It certainly looks better that way! 
It seems somebody took care of it already. => #5

**Comment by prateekiiest** [comment]
@kai5263499 , I worked on it. 
PR #5
